sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t elenagrigoruta/docker-react -f Dockerfile.dev .

script:
  - docker run elenagrigoruta/docker-react npm run test -- --coverage
